# Generated by Django 3.1 on 2020-08-24 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=80)),
                ('contact', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='static/images/user_img.jpeg', upload_to='user_profile_image/')),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
