# Generated by Django 3.1 on 2020-08-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='usr_id',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
