# Generated by Django 3.1 on 2020-08-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Users', '0002_auto_20200825_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='contact',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
