# Generated by Django 3.1 on 2020-08-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Users', '0003_auto_20200825_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='dob',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='lname',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
