# Generated by Django 3.1 on 2020-08-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Users', '0004_auto_20200826_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
