# Generated by Django 3.1 on 2020-09-24 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Users', '0006_auto_20200902_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequestModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_from', to='SM_Users.usermodel')),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_to', to='SM_Users.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllNotification',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('not_type', models.CharField(max_length=200)),
                ('notification', models.CharField(max_length=2000)),
                ('noti_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_from', to='SM_Users.usermodel')),
                ('noti_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_to', to='SM_Users.usermodel')),
            ],
        ),
    ]
