# Generated by Django 3.1 on 2020-09-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Users', '0008_friendrequestmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='allnotification',
            name='status',
            field=models.CharField(default='unread', max_length=20),
        ),
    ]
