# Generated by Django 3.1 on 2020-10-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Users', '0009_allnotification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='allnotification',
            name='my_notification',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
