# Generated by Django 3.1 on 2020-10-09 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Users', '0013_allnotification_noti_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allnotification',
            name='noti_date',
        ),
    ]
