# Generated by Django 3.1 on 2020-10-09 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Users', '0014_remove_allnotification_noti_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='allnotification',
            name='noti_date',
            field=models.DateTimeField(auto_now_add=True, default="2020-1-1 00:00:00.000000-00:00"),
            preserve_default=False,
        ),
    ]
