# Generated by Django 3.1 on 2020-10-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Users', '0015_allnotification_noti_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequestmodel',
            name='request_accepted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
