# Generated by Django 3.1 on 2020-11-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Users', '0017_auto_20201019_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesOnPosts',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_data', models.FileField(blank=True, upload_to='%d-%m-%y')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentsOnPost',
            fields=[
                ('comm_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=10000)),
                ('date_commented', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='%m-%d-%y')),
                ('comm_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Users.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllPosts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Users.commentsonpost')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Users.usermodel')),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Users.filesonposts')),
            ],
        ),
    ]
