# Generated by Django 3.1 on 2020-11-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Users', '0020_commentsonpost_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsonpost',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
