# Generated by Django 3.1 on 2020-11-24 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Users', '0021_auto_20201119_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='allnotification',
            name='post_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SM_Users.allposts'),
        ),
    ]
