# Generated by Django 3.1 on 2020-11-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Users', '0022_allnotification_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allnotification',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SM_Users.allposts'),
        ),
    ]
