# Generated by Django 3.1 on 2020-12-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Users', '0023_auto_20201124_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='allposts',
            name='post_header',
            field=models.CharField(default='', max_length=500),
        ),
    ]
