# Generated by Django 3.1 on 2020-12-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Users', '0024_allposts_post_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='about',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='lives_in',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='working_as',
            field=models.CharField(default='', max_length=500),
        ),
    ]
