# Generated by Django 3.1.7 on 2021-04-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Users', '0026_message_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='gender',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
